services:
  nginx:
    image: nginx:1.25-alpine
    container_name: cloudCore-gateway
    restart: unless-stopped
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./cors.conf:/etc/nginx/cors.conf:ro
    ports:
      - "80:80"
    networks:
      - cloud-core-net
    depends_on:
      - core-service
  core-service:
    build:
      context: ./core-service
    container_name: cloudCore-coreService
    restart: unless-stopped
    volumes:
      - ./core-service:/app
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: db
      POSTGRES_PORT: "5432"

      JWT_SECRET: ${jwt_secret}
      JWT_ALGORITHM: ${JWT_ALGORITHM:-HS256}

      AWS_COLLECTOR_URL: http://aws-collector:8080
      GCP_COLLECTOR_URL: http://gcp-collector:8080
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - cloud-core-net

  db:
    image: postgres:16-alpine
    container_name: cloudCore-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql:ro
    ports:
      - "127.0.0.1:5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - cloud-core-net

networks:
  cloud-core-net:
    driver: bridge

volumes:
  postgres_data:
    driver: local